epicsEnvSet("DEVICE_IP", "10.69.58.70")
epicsEnvSet("SYS",    "XF:31ID1-BI")
epicsEnvSet("DEV",    "EM:1")
epicsEnvSet("PORT",      "NSLS2_EM")
epicsEnvSet("DEVICE_SN", "E0009")  # Device serial number (used to select calibration file)
epicsEnvSet("QSIZE",     "20")
epicsEnvSet("RING_SIZE", "10000")
epicsEnvSet("TSPOINTS",  "1000")
epicsEnvSet("IP",        "$(DEVICE_IP):17")
epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES", "1000000")
